# SPDX-FileCopyrightText: 2023 XWiki CryptPad Team <contact@cryptpad.org> and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
services:
  cryptpad:
    image: "cryptpad/cryptpad:version-2024.6.0"
    hostname: cryptpad

    environment:
      - CPAD_MAIN_DOMAIN=https://your-main-domain.com
      - CPAD_SANDBOX_DOMAIN=https://your-sandbox-domain.com
      - CPAD_CONF=/cryptpad/config/config.js
      # Add SSO plugin from git's "main" branch, but can be a commit hash or a tag
      #- CPAD_PLUGIN_SSO=https://github.com/cryptpad/sso.git|main

      # Read and accept the license before uncommenting the following line:
      # https://github.com/ONLYOFFICE/web-apps/blob/master/LICENSE.txt
      # - CPAD_INSTALL_ONLYOFFICE=yes

    volumes:
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/files:/cryptpad/datastore
      # Useful if you want to store plugins and avoid downloading them all the time
      #- ./data/plugins:/cryptpad/lib/plugins
      - ./onlyoffice-dist:/cryptpad/www/common/onlyoffice/dist
      - ./onlyoffice-conf:/cryptpad/onlyoffice-conf

    ports:
      - "3000:3000"
      - "3003:3003"

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
